### ISSUE TITLE
LookupField - set doesn't work when I have bindings

### ISSUE THREAD

**Issue by ali-morina** [codaxy/cxjs#1002]
I have this example where I need to add some logic to the **set** function once the user selects a value from the LookupField dropdown. It's working fine on regular LookupField, but once I add bindings it ignores the **set** function. Is there a way I can resolve this issue? Example below as I tested in fiddle:

import { Controller, LabelsLeftLayout } from "cx/ui";
import { HtmlElement, LookupField } from "cx/widgets";

class PageController extends Controller {
  init() {
    super.init();
  }

  query(q) {
    if (!this.cityDb)
      this.cityDb = Array.from({ length: 100 }).map((_, i) => ({
        id: i,
        text: casual.city,
        date: Date.now()
      }));

    var regex = new RegExp(q, "gi");
    return new Promise((resolve) => {
      setTimeout(
        () => resolve(this.cityDb.filter((x) => x.text.match(regex))),
        300
      );
    });
  }
}

export const App = (
  <cx>
    <div class="widgets" controller={PageController}>
      <div layout={LabelsLeftLayout}>
        <LookupField
          label="Select"
          value={{
            bind: "$page.id",
            set: (value, { store }) => {
              // code reaches here if I remove bindings
              console.log(value);
              store.set("$page.id", value);
            }
          }}
          text-bind="$page.text"
          onQuery="query"
          minQueryLength={2}
          bindings={[
            {
              local: "$page.id",
              remote: "$option.id",
              key: true
            },
            {
              local: "$page.text",
              remote: "$option.text"
            },
            {
              local: "$page.date",
              remote: "$option.date"
            }
          ]}
        />
      </div>
    </div>
  </cx>
);

**Comment by mstijak** [comment]
You should also add set in your bindings. Binding takes precedence, if defined.

https://github.com/codaxy/cxjs/blob/master/packages/cx/src/widgets/form/LookupField.js#L67

**Comment by ali-morina** [comment]
Thank you @mstijak
