### ISSUE TITLE
Filtering and sorting data proxy

### ISSUE THREAD

**Issue by mstijak** [codaxy/cxjs#1013]
Grids, lists, and repeaters offer filtering and sorting capabilities. This works fine, but sometimes we need access to the data set after these operations are performed.

It would be nice to offer a component that would do these operations and write results back to the store as a mutable collection.

```
<RecordsProxy input-bind="records" output-bind="$filteredRecords" filterParams={...} onCreateFilter={...} sortField="">
<Grid records-bind="$filteredRecords" />
</RecodsProxy>
```
Alternatively, we could add an output field to the grid.

```
<Grid rows-bind="rows" />
```
However, this would be read-only.

**Comment by nebojsa-peric** [comment]
`onTrackMappedRecords` grid callback is added to support retrieving records after filtering/sorting has been applied.
