### ISSUE TITLE
LookupField issue

### ISSUE THREAD

**Issue by nebojsa-peric** [codaxy/cxjs#1084]
In lookup field's prepareData method there is a code which searches for the option based on the selected key(s):

```
function areKeysEqual(key1, key2) {
  if (!key1 || !key2 || key1.length != key2.length)
    return false;
  for (let i = 0; i < key1.length; i++)
    if (key1[i] != key2[i])
      return false;
  return true;
}
```

Is the comparison between keys intentionally non strict? We were adding lookup field for `Snap to ticks` chart feature which value can be either one of the 0, 1, 2 and false, however, lookup doesn't differentiate between `0` and `false` because `0 != false` isn't true. Funny enough, `0 != null` would be true :)

Same happens if one key is i.e. `3` and the other is `'3'`, which seems less problematic.

**Comment by mstijak** [comment]
This is a bug. It should be a strict check. PR?
