### ISSUE TITLE
Enable adding tooltip (and maybe other properties like class) to the icon in LookupField (maybe a button also) 

### ISSUE THREAD

**Issue by OKremenovic** [codaxy/cxjs#1136]
At the moment, we can only set a string as a value of the icon inside the LookupField. It would be nice if we could write something like this -

`<LookupField ... 
    icon={{
        text/name: 'fa-info-circle', 
        tooltip: 'A tooltip message'
    }}
/>`

This would be useful for LookupFields that behave differently than expected and we need to show it by placing an info icon. The expected user behavior would be to hover over this icon to see why it is placed inside the LookupField. 
Now, we can only put a tooltip on the LookupField level, and it does not show when we hover over the icon.

![hover-icon-lookup](https://github.com/codaxy/cxjs/assets/17080238/1ebe882e-cf33-4d44-8af3-8457906d6ef5)

**Comment by mstijak** [comment]
Fixed with #1143.
