### ISSUE TITLE
Infinite scrolling support in grids

### ISSUE THREAD

**Issue by david-bouyssie** [codaxy/cxjs#134]
Do you support infinite scrolling in grids?
In ExtJS it is implemented as a BufferedStore.

**Comment by mstijak** [comment]
No, not yet. It's on our roadmap to add buffered rendering for scrollable grids first. That should enable that grids play nicely when having a large number of records in the store. 
Infinite scrolling could theoretically be built on top of that, but it's a long way to go so we can't promise that feature yet.

**Comment by mstijak** [comment]
Since this is a feature request, for other people, if you wish this feature please give it a 👍.

**Comment by david-bouyssie** [comment]
Ok thank you for your answer.

**Comment by miguelocarvajal** [comment]
+1

**Comment by mstijak** [comment]
Infinite scrolling is now implemented.

https://docs.cxjs.io/examples/grid/infinite-scrolling
