### ISSUE TITLE
Feature request: desktop like theme

### ISSUE THREAD

**Issue by david-bouyssie** [codaxy/cxjs#135]
It would be nice to have a desktop like theme with minimum spacing between components (equivalent to the ExtJS classic one).
Developing "Single Page Applications" requires sometimes to display a lot of widgets in a single window, so having compact components is a need.

**Comment by mstijak** [comment]
In our new Material theme we have basic support for different sizes. 
You can just set
```
$cx-theme-base-size: 12px;
```
before this line:
```
@import "~cx-theme-material/src/variables";
```
in the root `index.scss` and you'll see it.

The new [TypeScript boilerplate project](https://github.com/codaxy/cx-typescript-boilerplate) is a good place to try that.

For other themes, it can also be done, but it's not that easy. It requires changing multiple variables.

**Comment by david-bouyssie** [comment]
Nice!

**Comment by mstijak** [comment]
I'm closing this issue since it's not clear if anything can/should be done here.
