### ISSUE TITLE
UploadButton does not respect `mod`

### ISSUE THREAD

**Issue by tymarats** [codaxy/cxjs#147]
Fiddle: https://cxjs.io/fiddle/?f=8mov7n6V

**Comment by tymarats** [comment]
Actually, this is a Material theme bug. The component respects `mod`, but the theme does not apply it as it does with buttons.

**Comment by mstijak** [comment]
@OKremenovic Isn't this finished? Should we close the issue?

**Comment by OKremenovic** [comment]
It's finished.
