### ISSUE TITLE
Password autofill is not caught

### ISSUE THREAD

**Issue by tymarats** [codaxy/cxjs#148]
When the password is autofilled from Chrome, it will not be recognized as filled until you trigger any event (keypress, mouse click) on the page.
![passwordautofill](https://cloud.githubusercontent.com/assets/491462/24962063/083d4eaa-1f9b-11e7-9576-45848ade5d30.png)

**Comment by mstijak** [comment]
Related to https://github.com/facebook/react/issues/1159.

**Comment by mstijak** [comment]
`trackBrowserAutofill` flag has been added in `17.5.1` that can be used to mitigate the issue until it's resolved within React.

```
<TextField value:bind="value" trackBrowserAutofill />
```
