### ISSUE TITLE
Calendar (and DateField) not working in Safari

### ISSUE THREAD

**Issue by tymarats** [codaxy/cxjs#161]
The problem lies along these lines:

```
   handleMouseDown(e){
      this.props.handleSelect(e, new Date(e.target.dataset.date));
   }
```

For selected date of May 11, 2017, `e.target.dataset.date` is `2017-5-11`, which cannot be parsed by Safari (see image below). `2017-05-11` would have worked fine, it seems.

![date](https://cloud.githubusercontent.com/assets/491462/26024965/0d9623bc-37de-11e7-8f04-4f24684054c2.png)

**Comment by mstijak** [comment]
Merged.
