### ISSUE TITLE
MonthField validation not working, values outside the allowed range not indicated

### ISSUE THREAD

**Issue by sasatatar** [codaxy/cxjs#171]
- MonthField validation is not working. When a required field is skipped, or an invalid value is given by keyboard, no feedback is given. 
- When using max and min values, values outside range should be indicated. 

```
<MonthField
                        label="Min/Max Value"
                        value={bind("validation")}
                        minValue={"2017-01-01"}
                        maxValue={"2017-12-31"}
                    />
```
Code above renders the following:
![image](https://cloud.githubusercontent.com/assets/5138412/26208260/f001576c-3be9-11e7-951a-37cda85c8c05.png)

All values look the same, with the difference that mouse selection of values outside the range is ignored, which is not very user-friendly.

**Comment by mstijak** [comment]
This is not implemented yet.
