### ISSUE TITLE
RedirectRoute not working correctly

### ISSUE THREAD

**Issue by sasatatar** [codaxy/cxjs#179]
If we have a route e.g. `~/messages` and inside it set up a default redirection to `~/messages/inbox`, the redirection seems to not work correctly. 
Example code for the `~/messages` route:
```
<Route route="~/messages(*splat)" url:bind="url" >
        <RedirectRoute route="~/messages" url:bind="url" redirect="~/messages/inbox" />
        {/* Other content and subroutes... */}
</Route>
```

The route gets correctly redirected to `~/messages/inbox` but the url immediately goes back to `~/messages` even though the state of the application suggests that the active route is indeed `~/messgages/inbox`.
The expected outcome is to have both state and the url correctly represented, showing `~/messages/inbox`.

**Comment by mstijak** [comment]
Fixed!
