### ISSUE TITLE
Routing problem

### ISSUE THREAD

**Issue by tymarats** [codaxy/cxjs#182]
Sometimes it happens that, when using browser Back button, the url changes correctly, but a part of the content is not rendered.

![clipboard01](https://user-images.githubusercontent.com/491462/26924684-277e5b3c-4c47-11e7-8cdf-bde27118242e.png)

**Comment by mstijak** [comment]
This is not a CxJS bug, but a problem in the app. I found this piece of code:
```              
<Link
  href:bind="$record.url"
  match="prefix"
  url:bind="url"
  onClick={(e, { store }) => {
      if (
        store.get("url") == store.get("$record.url") &&
          store.get("$record.sidebarView")
      ) {
        store.set("sidebar.view", store.get("$record.sidebarView"));
      }

      //problematic part
      if (!store.get("$record.sidebarView")) {
        store.set("sidebar.view", "main");
        if (window.innerWidth < 1000) {
          store.set("sidebar.hide", true);
        }
      }
    }}
/>
```
That means that `sidebar.view` is set only on navigation. It should be set when navigating back too... The solution would be to move this logic into initialization of each view which doesn't define any sidebar content.
