### ISSUE TITLE
If widget's if resolves to undefined, the widget is still visible

### ISSUE THREAD

**Issue by tymarats** [codaxy/cxjs#202]
The best way to describe it is with a fiddle :)
https://cxjs.io/fiddle/?f=b5u0C51B

**Comment by mstijak** [comment]
The problem here is that `if` is an alias for visible and we use the following code snippet to initialize `visible`:

```
if (typeof this.if !== 'undefined')
         this.visible = this.if;
```
It's easy to get around this issue. Just use `visible` or add double negation `if={!!cfg.bogus}`.

I'm not sure what is the best way to fix this, so let's leave the issue open.
