### ISSUE TITLE
Option to hide axis labels, but show the axis

### ISSUE THREAD

**Issue by sasatatar** [codaxy/cxjs#204]
Currently, it is only possible to hide chart axes entirely using `hidden` property.
```
<Chart offset="5 0 -20 25" axes={{
    x: { type: CategoryAxis, hidden: true },
    y: { type: NumericAxis, vertical: true, hidden: true } }}>
    <LineGraph data={{bind: "$page.speeding.events"}} 
        xField="month" 
        yField="count" />
</Chart>
```
Sometimes, it is only needed to hide the labels, but preserve the axes. Currently, this feature is not supported, but css classes `.cxe-numericaxis-label` and `.cxe-categoryaxis-label` have to be overwritten using `display: none;`. 
It would be useful if this could be achieved with a custom property, e.g. `hideLabels: true` or `showLabels: false`.

**Comment by mstijak** [comment]
There is now a new configuration option called `hideLabels` available for all Axis types.
