### ISSUE TITLE
cx-google-maps

### ISSUE THREAD

**Issue by tymarats** [codaxy/cxjs#217]
We now have a [CxJS wrapper](https://github.com/codaxy/cx-google-maps) for a few [react-google-maps](https://github.com/tomchentw/react-google-maps) components. It might be useful to developers dealing with maps in their applications, so it would be a good idea to mention its existence somewhere in Cx.

**Comment by mstijak** [comment]
The package is now listed at https://docs.cxjs.io/intro/npm-packages. Thanks
