### ISSUE TITLE
Add Pagination documentation to the cxjs docs

### ISSUE THREAD

**Issue by yrodrigez** [codaxy/cxjs#222]
Such as how can i change it's styles (size, color and stuff) and

**Comment by mstijak** [comment]
We have added the `Pagination` configuration properties to this page: https://docs.cxjs.io/examples/grid/pagination

Regarding styling, I would recommend using CSS and `mod`. For example,
```
<Pagination mod="hollow" />
```
will render
```
<div class="cxb-pagination cxm-hollow">
...
</div>
```
You can now use the `.cxb-pagination.cxm-hollow` CSS class to override appearance for your particular instance. If you want to want change how pagination looks globally you should check Pagination.scss and other SCSS files and variables. 

I'm going to close the issue, feel free to reopen it if you have more questions.
