### ISSUE TITLE
Grid component showCursor bug

### ISSUE THREAD

**Issue by tymarats** [codaxy/cxjs#232]
Not sure if this one can be reliably reproduced, but it happens in this scenario: 
  - the grid's collection (`records`) is empty
  - the grid has `emptyText` defined and 
  - the grid has been clicked on

![clipboard01](https://user-images.githubusercontent.com/491462/29109900-1237f7a0-7ce5-11e7-850b-529550bb9cfb.png)

**Comment by mstijak** [comment]
Fixed
