### ISSUE TITLE
Timezone seems to be different for some fields

### ISSUE THREAD

**Issue by raulQA** [codaxy/cxjs#244]
Hi all.

I have check that in a labtop with a timezone configured (for example in London-UK UTC+0), and that labtop is located in another timezone (Madrid-Spain UTC+1), a strange behaviour happends:

![to_delete](https://user-images.githubusercontent.com/31350404/29763674-101f45d6-8bcc-11e7-9614-19498fbc69fd.png)

That is a normal behaviour if an user is traveling a lot with their labtop

could you have a look please?

**Comment by tymarats** [comment]
As I previously stated, this is exactly what's expected (your computer is in UTC+0 timezone, but the DST is currently active, so it's effectively UTC+1) and is not an issue. However, it would be interesting to see your other scenario (the one with the date filter in the grid), so could you please post that one here, too? Comments on that one might be useful for other developers.

**Comment by raulQA** [comment]
![to_delete1](https://user-images.githubusercontent.com/31350404/29764241-4bd3e904-8bce-11e7-9ef3-da00668a46e3.png)
![to_delete2](https://user-images.githubusercontent.com/31350404/29764245-4f081c08-8bce-11e7-9a81-0423a050cc40.png)

**Comment by raulQA** [comment]
I guess that is owing to the DST commented... owing to it is using UNIX tiemstamp which is one hour less only using DateField, it is sent to the server that date minus one hour

**Comment by mstijak** [comment]
DateField widget always reports 00:00 time of the selected date and writes the value in ISO 8601 format to the CxJS data store. This might not be exactly what you need, so I would recommend that you take the date from the store and apply date transformations before sending it to the server, e.g. format it differently.

**Comment by mstijak** [comment]
Time part of a date is always questionable, so if you want ultimate precision you can use DateTimeField.
https://docs.cxjs.io/widgets/date-time-fields

**Comment by mstijak** [comment]
I'm closing this issue since it's non-actionable.
