### ISSUE TITLE
Repeater `sorters` not working when record name is redefined

### ISSUE THREAD

**Issue by tymarats** [codaxy/cxjs#250]
For example:

```
<Repeater records:bind="$page.records" recordName="$point" keyField="assetId" sorters:bind="$page.sorters">
...
```

In this case, sorters will not be applied.

**Comment by mstijak** [comment]
I have added a test which confirms that sorters work:
https://github.com/codaxy/cxjs/commit/a90cd44228b2514619f4e45c9f206678bc02a439

Maybe the problem lies in sorters data?

**Comment by tymarats** [comment]
Example:

https://fiddle.cxjs.io/?f=39AKDPvt

I'm assuming this does not work because the grid is defined over `$record`s and the 2nd chart is defined over `$point`s and the sorters of the two are therefore incompatible?

**Comment by tymarats** [comment]
...which is exactly the case. Ok, makes sense.
