### ISSUE TITLE
Add ProgressBar control

### ISSUE THREAD

**Issue by mstijak** [codaxy/cxjs#255]
Although it's very simple to implement, we should include it.

**Comment by yrodrigez** [comment]
Maybe ButtonProgressBar :) that would be awesome

**Comment by yrodrigez** [comment]
![rtegewryrtye5](https://user-images.githubusercontent.com/6799275/31608041-b75ed166-b266-11e7-9c39-fe5d5a80a609.gif)
Something like this maybe

**Comment by mstijak** [comment]
@yrodrigez This is an interesting idea. I'm not sure if something like this is commonly used, so it might be better to implement ProgressButton as a functional component in your application. Here's a quick demo:
https://fiddle.cxjs.io/?f=puBIRMCM

**Comment by mstijak** [comment]
Fixed with #296.
