### ISSUE TITLE
NumberField scrolling disable

### ISSUE THREAD

**Issue by tymarats** [codaxy/cxjs#261]
Sometimes it makes sense to disable scrolling feature on `NumberField` (for example, when number fields are a part of a longer form, one may accidentally change their value while trying to scroll through the form). Maybe that already exists, but is not documented?

**Comment by mstijak** [comment]
This is actually supported by specifying `reactOn="enter change blur"`. Default value is "enter change wheel blur".

I'm not sure if there should be a dedicated property.
