### ISSUE TITLE
package.json causing error when running npm install

### ISSUE THREAD

**Issue by adamkpurdy** [codaxy/cxjs#279]
Hello everyone!

I'm new to cxjs, and I was looking into getting my developers into your framework. Looks like you guys have a lot of good stuff cooking up. Unfortunately I'm not able to grab master and install the dependancies, or get the Step by Step app to kick off properly.

Here is my error for cloning master:

```npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/adamkpurdy/.nvm/versions/node/v7.2.1/bin/node" "/Users/adamkpurdy/.nvm/versions/node/v7.2.1/bin/npm" "install"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10

npm ERR! Unsupported URL Type: link:./packages/cx
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adamkpurdy/Sites/samples/react-box/cx-box/cxjs/npm-debug.log
```

Looks like line 96 in the package.json file.

**The Step by Step instructions in the docs for the getting-started app is also falling to start:

```
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/adamkpurdy/.nvm/versions/node/v7.2.1/bin/node" "/Users/adamkpurdy/.nvm/versions/node/v7.2.1/bin/npm" "start"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! cx-getting-started@1.0.0 start: `webpack-dev-server --open`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the cx-getting-started@1.0.0 start script 'webpack-dev-server --open'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cx-getting-started package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --open
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cx-getting-started
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cx-getting-started
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adamkpurdy/Sites/samples/react-box/cx-box/cx-getting-started/npm-debug.log
```

**Comment by mstijak** [comment]
This is a monorepo containing many packages. We decided to interlink packages, since it's supported by  npm 5 and yarn 1.0. It's much easier to work that way. Please upgrade npm on your machine and everything should work fine.

**Comment by sasatatar** [comment]
I think Adam was referring to `npm install`, and indeed it breaks even with the latest version of Node:
```
$ npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:./packages/babel-preset-cx-env

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sasa\AppData\Roaming\npm-cache\_logs\2017-10-09T07_47_49_475Z-debug.log
```
So, until npm picks up the pace, it's best to use `yarn install` or just `yarn`. 
Adam, you can get yarn package manager here: https://yarnpkg.com/en/

**Comment by mstijak** [comment]
You're right. I saw somewhere that npm v5 supports `link:` packages, so I thought an upgrade would resolve the issue.

**Comment by mstijak** [comment]
It seems that npm changed their plan and decided to use `file:` instead of `link:` for symlinks.

https://github.com/npm/npm/pull/15900
https://github.com/yarnpkg/yarn/issues/4212

We must choose between yarn or npm. 

`file:` is supported by both, but behaves differently. In favor of yarn, I would really like to try out workspaces and yarn upgrade-interactive is a life saver.

**Comment by adamkpurdy** [comment]
Thanks fellas. It worked like a charm using yarn. I'll get back to my research and start playing around with this. Again, your work on this looks great, and thank you!

**Comment by ajaymarathe9** [comment]
> It seems that npm changed their plan and decided to use `file:` instead of `link:` for symlinks.
> 
> [npm/npm#15900](https://github.com/npm/npm/pull/15900)
> [yarnpkg/yarn#4212](https://github.com/yarnpkg/yarn/issues/4212)
> 
> We must choose between yarn or npm.
> 
> `file:` is supported by both, but behaves differently. In favor of yarn, I would really like to try out workspaces and yarn upgrade-interactive is a life saver.

Replace `link` with `file` it working thanks.
