### ISSUE TITLE
Need update npm and reactjs to latest for the demo - can't run....

### ISSUE THREAD

**Issue by PolywickStudio** [codaxy/cxjs#326]
$npm start

> cx-starter-kit@16.6.0 start starter
> webpack-dev-server --config config/webpack.dev.js --open

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8088
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cx-starter-kit@16.6.0 start: `webpack-dev-server --config config/webpack.dev.js --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cx-starter-kit@16.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     2017-12-03T22_28_31_154Z-debug.log
----------------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\USERX\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle cx-starter-kit@16.6.0~prestart: cx-starter-kit@16.6.0
6 info lifecycle cx-starter-kit@16.6.0~start: cx-starter-kit@16.6.0
7 verbose lifecycle cx-starter-kit@16.6.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle cx-starter-kit@16.6.0~start: PATH: C:\Users\USERX\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;
9 verbose lifecycle cx-starter-kit@16.6.0~start: CWD: C:\Users\USERX\polywick-currents\polywick-website10\pp4
10 silly lifecycle cx-starter-kit@16.6.0~start: Args: [ '/d /s /c',
10 silly lifecycle   'webpack-dev-server --config config/webpack.dev.js --open' ]
11 silly lifecycle cx-starter-kit@16.6.0~start: Returned: code: 1  signal: null
12 info lifecycle cx-starter-kit@16.6.0~start: Failed to exec start script
13 verbose stack Error: cx-starter-kit@16.6.0 start: `webpack-dev-server --config config/webpack.dev.js --open`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\USERX\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\USERX\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid cx-starter-kit@16.6.0
15 verbose cwd C:\Users\USERX\polywick-currents\polywick-website10\pp4
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\USERX\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error cx-starter-kit@16.6.0 start: `webpack-dev-server --config config/webpack.dev.js --open`
22 error Exit status 1
23 error Failed at the cx-starter-kit@16.6.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mstijak** [comment]
You should change the application port in weback config file. You're
probably running another app on the same port...

**Comment by PolywickStudio** [comment]
Ok, it worked.

Reference for ppl. trying to fix this bug:
1) change -> \config\webpack.dev.js to another port.

2) npm update the dependencies to latest
`    "babel-preset-env": "^1.6.1",
    "base-64": "^0.1.0",
    "casual": "^1.5.14",
    "cx": "^17.10.9",
    "cx-react": "^17.10.0",
    "cx-theme-material": "^17.10.0",
    "deep-equal": "^1.0.1",
    "marked": "^0.3.6",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "whatwg-fetch": "^2.0.3"
`
