### ISSUE TITLE
GoLang, PHP, ASP.NET?

### ISSUE THREAD

**Issue by PolywickStudio** [codaxy/cxjs#341]
Does CxJS work with other back-ends, such as GoLang, PHP and ASP.NET?

**Comment by mstijak** [comment]
CxJS is back-end agnostic. It's the job of the developer to fetch data from the server, which can be written in any language, and put in the store. It's the same for write operations.

We used CxJS with back-ends based on .NET, Node.js, Firebase, Java. It really doesn't matter. You can simply use `fetch` or specialized client libraries, e.g. `firebase`. In our Demo Apps section, you can find examples of connecting to ASP.NET and Firebase.
