### ISSUE TITLE
Jquery-QueryBuilder CX integration

### ISSUE THREAD

**Issue by yrodrigez** [codaxy/cxjs#343]
Im trying to create an integration of the [QueryBuilder](https://github.com/mistic100/jQuery-QueryBuilder) in CX  and i need to create the inputs with the CX components just like date fields use a cx `DateTimeField`  

My Component looks like this (shorted)

```
class QueryBuilder extends PureContainer {
      declareData(){
        return super.declareData([filters: undefined], ...arguments);
      }
....
    prepareData(context, instance) {
       super.prepareData(context, instance);
       instance.mappedRecords = this.dataAdapter.mapRecords(context, instance, instance.data.filters, instance.store, this.recordsBinding);
       debugger;
  }
....
     render(context, instance, key) {
        return <Component
          key={key}
          instance={instance}
          context={context}
         />
  }
}
class Component extends VDOM.Component {
...
    componentDidMount() {
      this.fetchFilters().then(response => {
        Console.debug('queryBuilder response', response);
        filters = response.data.result.contactsQBFilters;
        Console.debug('filters', filters);
        this.setState({loading: false});
        this.createQueryBuilder(filters);
      });
    }
...
    createQueryBuilder(filters) {
    let {plugins, icons, rules, readOnly, nlRules} = this.props.instance.data;

    let container = $(`#${this.props.instance.key}-query-builder`);

    this.props.instance.set('filters', filters);
    container.queryBuilder({
      filters,
      plugins,
      icons,
    });
   }
  }
}

```
the problem comes when im trying to map the filter's values to the component... the array look like this: 

```
[
  {name_orig: "@lastName", targetSchema: "cis:contactsConsolidated", label: "Contact Last Name", expr: {…}, format: ".*", …},
  {name_orig: "@firstName", targetSchema: "cis:contactsConsolidated", label: "Contact First Name", expr: {…}, format: ".*", …},
  {name_orig: "@blackListEmail", targetSchema: "cis:contactsConsolidated", label: "Contact Blacklist Email", expr: {…}, type: "integer", …},
  {name_orig: "@orgEntityId", targetSchema: "cis:contactsConsolidated", label: "Organizational Entity Id", expr: {…}, type: "integer", …}
]
```

because when i use `this.props.instance.set('filters', filters);`  the `prepareData` method is not being called neither the filters are setted... in addition, if i use `this.props.instance.data.filters = filters;` filters have data but the  `prepareData` method is also not being called

**Comment by mstijak** [comment]
I'm not sure if that is possible. It's very hard to mix different things. You may easily embed a jQuery component inside a Cx component, but I don't see a way to use CxJS inside to render controls.

The common way for embedding jQuery controls is to render an empty div element, and then invoke a jQuery plugin in `componentDidMount` and hook up events. Also, `shouldComponentUpdate` should always `return false`. Please note that what happens inside that div is not anymore in the realm of CxJS or React.
