### ISSUE TITLE
List and Grid: Scroll selection into view

### ISSUE THREAD

**Issue by tymarats** [codaxy/cxjs#346]
It would be useful to have an option like `scrollSelectionIntoView` which would ensure that the selected item of a `List`/`Grid` becomes visible, even when scrolled out of view initially and then set programmatically (without a user actually clicking the item).

**Comment by mstijak** [comment]
Fixed in 18.1.15!

**Comment by yrodrigez** [comment]
I tribu i do not understand this feature

**Comment by mstijak** [comment]
@yrodrigez: If the selection is updated programmatically (through the store), the grid will scroll to find it and show it if `scrollSelectionIntoView` flag is set on the grid.
