### ISSUE TITLE
RFC: Store refs

### ISSUE THREAD

**Issue by mstijak** [codaxy/cxjs#347]
It's very common that within one controller the same data object is accessed multiple times, e.g. in `init`, `get` and `set` operations.

```js
export default class extends Controller {
  onInit() {
    this.store.init('$page.pageSize', 100);
  }

  setPageSize(pageSize) {
    this.store.set('$page.pageSize', pageSize);
  }
}
```

Would it be better to declare a reference first and then use it elsewhere?

```js
export default class extends Controller {
  storeRefs = {
    pageSize: '$page.pageSize'
  }

  onInit() {
    this.pageSize.init(100);
  }

  setPageSize(pageSize) {
    this.pageSize.set(pageSize);
  }
}
```

There would be fewer magic strings and it might be easier to rename data bindings.

What would be the best syntax way to declare bindings?

**Comment by yrodrigez** [comment]
this would be cool, no more strings... i was thinking on doing something like this

**Comment by yrodrigez** [comment]
is there any news about this?

**Comment by mstijak** [comment]
Nothing yet. We're still not 100% sure if this is a good idea.

**Comment by mstijak** [comment]
Replaced by #487 .
