### ISSUE TITLE
Request for kanban view

### ISSUE THREAD

**Issue by handoyo** [codaxy/cxjs#353]
I would like to request for kanban view in codaxy. Like this one: [https://www.jqwidgets.com/react/react-kanban/](url). Thanks.

**Comment by mstijak** [comment]
Have you seen this demo? https://fiddle.cxjs.io/?p=H9Bb4Kf2

Which features do you miss?

**Comment by handoyo** [comment]
No I haven't see that demo yet. Is it published at CxJS example? Does it has the add and edit feature?

**Comment by mstijak** [comment]
Yes, it's listed at https://cxjs.io/examples. Add/edit/remove are not implemented in the example, but it should not be too hard to add that.

**Comment by handoyo** [comment]
Thanks for the information. I will learn from the example.
