### ISSUE TITLE
Button dismiss attribute not documented + onClick does not fire if dismiss is used

### ISSUE THREAD

**Issue by sasatatar** [codaxy/cxjs#354]
```
<Button label="Click me!" onClick={() => console.log('Clicked!')} dismiss />
```
In the example above, `onClick` callback is not called because `dismiss` attribute is used. In some cases we may want to both dismiss the overlay and invoke the `onClick` callback if one is defined. 

Also, `dismiss` attribute should be documented.

**Comment by mstijak** [comment]
If return value of `onClick` `=== false` we should cancel dismissal.
Do we need `onDismiss` callback on Overlays?

**Comment by sasatatar** [comment]
It looks to me that the above approach (`onClick` is invoked and has the possibility to cancel the dismissal), covers pretty much all possible use-cases where we might want to use `onDismiss` rather than `onClick + dismiss`, so we might not need it?

**Comment by mstijak** [comment]
Ok

**Comment by sasatatar** [comment]
If dismissal is canceled when `onClick` returns false, then `onClick` would by default cancel the dismissal, given that `onClick` is typically used without a return value, which is equivalent to returning `false`. This means, a user could use a Button with both `onClick => void + dismiss` and expect it to work.

Would it maybe make more sense that the dismissal is canceled if `onClick` returns `true` rather than `false`, to make the intent more explicit?

**Comment by mstijak** [comment]
`undefined !== false`

**Comment by sasatatar** [comment]
OK, that resolves it :)
