### ISSUE TITLE
LookupField appears populated when selection id is set to an empty string

### ISSUE THREAD

**Issue by sasatatar** [codaxy/cxjs#362]
In order to clear the selection in a LookupField, the binding containing the selection id is set to `null`. 
When receiving data from the server, properties without values are set to empty strings (`''`), and in such cases LookupField looks as if it contains a selection (clear button is displayed). 
It would be useful if LookupField would treat the empty string values the same as `null` and would apper without selection, so that we don't have to map the data to replace empty strings with explicit `null` values.

Example: https://fiddle.cxjs.io/?f=coFv8vWM

**Comment by mstijak** [comment]
This is the expected behavior. `null != ''`.  I wouldn't do anything here.

You can simply do `store.set('value', serverValue || null)` and it should work.

**Comment by sasatatar** [comment]
I agree, this makes perfect sense. Just for reference, in cases data is an object, to avoid manually replacing empty strings with `null`s for each property, it's easiest to do it with a `for` loop.
