### ISSUE TITLE
Internal working of visible attribute in functional components might be unnecessary 

### ISSUE THREAD

**Issue by sasatatar** [codaxy/cxjs#381]
It's a common use case to have a func. component that passes most of the props to one of its child components. 
But if `visible` is one of them, and `visible={false}` is passed to a functional component, it will not even get rendered. 
It should perhaps be left to the user to decide how to use `visible` attribute. If it is indeed intended not to render the entire component if `visible={false}`, it is simple to implement it.
This way I feel we get little and lose a lot.

**Comment by mstijak** [comment]
If you want to pass `visible` to child elements use another name. `visible` is reserved for what it currently does. Changing the behavior might lead to unexpected controller initialization and other unexpected side effects.

**Comment by sasatatar** [comment]
That is a good point. In that case, I would just update the docs to include this info.

**Comment by sasatatar** [comment]
There are a couple of related issues to reserved properties that should perhaps make us reconsider this implementation:
* If a Functional component has conditional rendering (basically a bound `visible` property), it makes the use of `visible` attribute impossible on any of the children. Consequently, a Window child component has its own `visible` property overwritten and is displayed immediately, which is not the desired behavior. 
* Another inconsistency is that bound `visible` property on a Functional component is not working in cases where `<Rescope></Rescope>` is used as a root wrapper inside the component (which is a common design pattern) since the `visible` property passed behind the scenes now has the incorrect path. 

Although both of these issues can be bypassed (by renaming the `visible` property and wrapping a `Rescope` with a `PureContainer`), it feels like behind the scenes props handling causes more trouble than good, since these issues can cause many undesired behaviors that are really hard to debug.

**Comment by sasatatar** [comment]
I know it's potentially a breaking change, but in the long run, it's better to change this now than later. I would be happy to go through our entire code base and make the necessary changes, and also prepare the announcement and instructions for the users. :)

**Comment by mstijak** [comment]
It might not be a breaking change if we wrap the contents inside a <PureContainer layout={UseParentLayout}>. That would work for `Rescope` and for form fields.

I guess wrapping should be done only if `visible` or `controller` or `outerLayout` are set on the component.
