### ISSUE TITLE
Add scale and offset properties to the NumberField

### ISSUE THREAD

**Issue by sasatatar** [codaxy/cxjs#387]
It's a common pattern to keep the number values in one format and display them in another, for example, value 0.5 is displayed as 50%, or 1000 as 1K...

For such cases it would be useful to have `scale` and `offset` properties for the NumberField:

```
<NumberField scale={100} format={p} />
<NumberField scale={1/1000} format="suffix; K" />
<NumberField offset={273.15} format="suffix; Kelvin" />
```
Simple way for the developer to reason about it:
- when `scale` is defined, NumberField will display a `value` multiplied by `scale`
- when `offset` is defined, NumberField will display a `value` increased by `offset`.

**Comment by mstijak** [comment]
This is now implemented. It would be great to add a small example in the docs.

**Comment by ognjenst** [comment]
@mstijak I have fixed this in the docs, but there is a problem with these two options, they are not working properly. On each focus on the field, the value is changed.

**Comment by mstijak** [comment]
It should be working. We use it in multiple places. Can you provide a
fiddle example?
