### ISSUE TITLE
FlexBox target="tablet"

### ISSUE THREAD

**Issue by tymarats** [codaxy/cxjs#388]
`FlexBox target="tablet"` breaking point may be set too low (1000px). iPad, for example, has wide resolution of 1024px and there's a huge gap between this and desktop screens (1920px) or even  majority of laptop ones (1280px). It makes sense either to up this breaking point at least to 1024, or to define one more target, `lg-screen`, for example.

**Comment by mstijak** [comment]
Fixed. You can further tweak screen widths using SCSS.
These are new default values:
```
// SCREEN SIZE
$cx-screen-size-small:  400px !default;
$cx-screen-size-medium: 800px !default;
$cx-screen-size-large: 1300px !default;
$cx-screen-size-extra-large: 1800px !default;
```
