### ISSUE TITLE
BUG DateTimePicker

### ISSUE THREAD

**Issue by yrodrigez** [codaxy/cxjs#395]
There is a bug with date time 

[Evidence](https://fiddle.cxjs.io/?f=OBGtmO3b)
I think it's related with the timezone because when the time changes to the spring time the time picker wont' allow you to pick an hour lesser than 2am

**Comment by mstijak** [comment]
This happens only on Mar 25, 2018. It's the last Sunday of March when time is adjusted for daylight saving. I'm not sure if this is really a bug or how to fix this. If you pick a later date , everything works as expected.
