### ISSUE TITLE
Grid sorters

### ISSUE THREAD

**Issue by yrodrigez** [codaxy/cxjs#397]
Grid sorters is firing a function that orders the grid's field by default array string sorter and does not takes into account the sorting trigger added to the Controller, 
[Evidence](https://fiddle.cxjs.io/?f=SXjrT9BJ)

**Comment by mstijak** [comment]
Grid sorters is a bindable property that allows sorting instructions to be read for server-side sorting scenarios.

Here's an example: 
https://docs.cxjs.io/examples/grid/pagination

**Comment by sasatatar** [comment]
I think yrodrigez is referring to string sorting applied to the second column. 
I would suggest converting the `profilesCount` values from strings to numbers, in that case, the automatic sorting will work as expected.
Example: https://fiddle.cxjs.io/?f=fE5FZDJi

**Comment by yrodrigez** [comment]
Thanks for the quick answer, but what my issu is that is there any way to make this custom operations to do this thing, because when you use this combined with pagination, the sorting is applied with a "default strings array sort" and we need to use this for a lot of scenarios such as dates, strings not matter the lower caps case, plus if you use this with pagination, the grid will only sort the records in the current "page" and this is not out required behaviour

**Comment by mstijak** [comment]
This should work if you add the remoteSort flag and bind sorters to the
grid. I don't see any problems on our side.

You can also use sortField on a column to sort by some other field, e.g. a
calculated value.

**Comment by yrodrigez** [comment]
Oh didn't know about the `remoteSort` Flag... sorry and thanks i was looking for it in the documentation and couldn't find it but it works.
