### ISSUE TITLE
Incorrect DateField validation

### ISSUE THREAD

**Issue by OKremenovic** [codaxy/cxjs#402]
Although the selected date is the same as the maxValue date, the DateField is shown as invalid. When the DateField loses focus, the invalid error disappears.

![date-field-maxvalue](https://user-images.githubusercontent.com/17080238/38134085-f018938e-3411-11e8-9c9c-5eb454e36d10.gif)

**Comment by mstijak** [comment]
After inspection, it seems this is not a bug in CxJS.
