### ISSUE TITLE
NumberField should not react on scroll by default

### ISSUE THREAD

**Issue by sasatatar** [codaxy/cxjs#407]
By default, NumberFields react on scroll which can often go unnoticed by the user.
This option, as much as it can be useful, should perhaps be disabled by default.

Currently, `reactOn="enter blur change"` can be used to disable this behavior, but this is rather unintuitive and tedious.

Maybe we could ntroduce a special flag to enable this feature? Some suggestions:
- `scrollable`
- `scrollStep` or `stepScroll`
- `incrementScroll`

**Comment by mstijak** [comment]
I agree that it might be better to turn the wheel off by default, but I'm not sure if additional fields are required. `NumberField` already supports the `increment` field.

https://docs.cxjs.io/widgets/number-fields#increment

**Comment by sasatatar** [comment]
We could perhaps just emphasize in the docs that this feature will be enabled if `increment` is set explicitly.

**Comment by mstijak** [comment]
But that's not true. If the step is not explicitly set, it's calculated relative to the current value.

I guess we should simply change
```
NumberField.prototype.reactOn = "enter change wheel blur";
```
to
```
NumberField.prototype.reactOn = "enter change blur";
```
and make sure it's properly documented how to enable the wheel.

I'm not sure if NumberField should react to `change` either as it behaves strangely in some situations.
