### ISSUE TITLE
DateField April bug

### ISSUE THREAD

**Issue by tymarats** [codaxy/cxjs#409]
We're getting reports from multiple users of one project that they "cannot select April, but have two Marches instead" in DateFields. Although I cannot seem to replicate that exact behavior, there is a certain quirk that might be connected to the issue. Please, take a look at this fiddle: https://fiddle.cxjs.io/?f=9CNtAMYx

**Comment by mstijak** [comment]
I thought it's an April Fools' joke :)

**Comment by raymondbarnes** [comment]
No please no! I thought the users were going crazy then it happened to me today!
