### ISSUE TITLE
Field repeater within LabelsLeftLayout bug

### ISSUE THREAD

**Issue by tymarats** [codaxy/cxjs#414]
`LabelsLeftLayout` does not work well with fields within repeaters. See fiddle: https://fiddle.cxjs.io/?f=1d9BXacd

**Comment by mstijak** [comment]
In order for this to work, you must use `UseParentLayout` on the repeater.

https://fiddle.cxjs.io/?f=SbhRdgn9

There was a problem with the Repeater widget, so this works only with the latest version of CxJS.

**Comment by mstijak** [comment]
FYI, https://docs.cxjs.io/concepts/inner-layouts#useparentlayout
