### ISSUE TITLE
Documentation for Cx component?

### ISSUE THREAD

**Issue by yrodrigez** [codaxy/cxjs#430]
I remember using this component for custom rendering inside of a `VDOM.Component`

It would be nice to have some documentation about how to use it in custom components

here is the link to the component
https://github.com/codaxy/cxjs/blob/master/packages/cx/src/ui/Cx.js

**Comment by mstijak** [comment]
Yes, we definitely miss this. This page should explain the use-case of Cx widgets within a React application.
