### ISSUE TITLE
Implement groupingParams and onCreateGroupings

### ISSUE THREAD

**Issue by mstijak** [codaxy/cxjs#439]
This should work similar to how `filterParams` and `onCreateFilter` work on the grid.

**Comment by mstijak** [comment]
The feature is implemented and works like this:

```
<Grid     
     groupingParams:bind="$page.grouping"
     onCreateGrouping={(groupingParams) => [
         {key: {}, showFooter: true},
         ...(groupingParams || []).map(x => x.id)
     ]}
```

Is there a better name for the function from `onCreateGrouping`?

**Comment by nikolatechie** [comment]
`onCreateGrouping` has been renamed to `onGetGrouping`. Here's an example: https://docs.cxjs.io/examples/grid/dynamic-grouping
