### ISSUE TITLE
Add support for footer with totals in tree grid

### ISSUE THREAD

**Issue by nebojsa-peric** [codaxy/cxjs#470]
It would be nice to be able to show footer row with totals when using tree grid. Also, you should be able to define how the values for this row are calculated, i.e. to be able to specify that only leaf elements should be considered when calculating those values.

**Comment by mstijak** [comment]
This is now possible. If you add the `fixedFooter` flag, the footer will be rendered even if grouping is not defined. In column footers, you can bind to any value in the store.
For example, if aggregate values are stored in the variable `total`, you can render the footer like this:
```js
{ field: 'volume', footer: { tpl: '{total.volume:n;2}' } }
```

**Comment by nebojsa-peric** [comment]
Working fine, except for the last row not being fully visible:
![image](https://user-images.githubusercontent.com/30226963/43305188-13a08be6-9177-11e8-8408-04ab7f33765c.png)
