### ISSUE TITLE
How to use with VueJs?

### ISSUE THREAD

**Issue by biapar** [codaxy/cxjs#488]
How to use with VueJs?

**Comment by mstijak** [comment]
Unfortunately, Vue is not supported. CxJS works on top of React. Preact should also work, however, we do not officially support it or test CxJS with it.

**Comment by biapar** [comment]
Have you Vue.JS on roadmap?

**Comment by mstijak** [comment]
No. React does its job very well for now.

**Comment by biapar** [comment]
So, if CXJS don't work without React, I think that don't work with VUE.JS. 
Thanks for you info.
