### ISSUE TITLE
How to save layout and widget position and how to create new widget?

### ISSUE THREAD

**Issue by biapar** [codaxy/cxjs#489]
How to save layout and widget position and how to create new widget?

**Comment by mstijak** [comment]
If you're referring to dashboards, widget configuration is a simple array. You can simply add a trigger and save it on each change.

Check out `app/dashboard/Controller.js` in https://codesandbox.io/s/42n5l3z3xw.

New dashboards widgets can be created out of existing CxJS widgets. Creating new CxJS widgets requires a basic understanding of CxJS data-binding and React. I would recommend reading the source code for the existing widgets. What kind of a widget you have in mind?
