### ISSUE TITLE
Documentation for update functions

### ISSUE THREAD

**Issue by alumezi** [codaxy/cxjs#499]
The updateTree function does not have an example on the docs. We need more information on how it works.

**Comment by sasatatar** [comment]
The docs with examples are underway, but I'll try to give a quick answer here until then.
```
function updateTree(
    array: any[],
    updateCallback: (item: any, index: number) => any,
    itemFilter?: (item: any, index?: number) => any,
    childrenField?: string,
    removeFilter?: (item: any, index?: number) => any,
): any[];
```
`updateTree` is a pure function, meaning it takes the tree, makes some updates and returns an updated copy of the tree. The original tree is left unchanged.
- `array` is the tree structure, that is an array of objects/tree items with their children subarrays stored under the `childrenField`, which is by default `children`.
- `updateCallback` is the update function that will be executed on each tree item that passes the filter, if there is one set. `updateCallback` takes two arguments, `item` and `index`, and returns an updated copy of the tree item. This should be a pure funciton that makes no changes on the original `item`.
- `itemFilter` is a predicate function, meaning, it receives the tree item and its index as arguments, and returns `true` or `false`. Only items for which `itemFilter` returns `true` will get updated.
- `childrenField` is the name of the property under which child items are stored. By default, it's `children`.
- `removeFilter` is another predicate function that receives tree item and its index as arguments and returns either `true` or `false`. Each tree item for which `removeFilter` returns `true` is removed from the updated tree.

The `array` and `updateCallback` parameters are obligatory, whereas `itemFilter`, `childrenField` and `removeFilter` are optional.

Hope this helps. Let me know if you have any other qustions. We'll leave the issue open until the docs are complete.

**Comment by alumezi** [comment]
Thanks, that is very helpful!
