### ISSUE TITLE
Scroll of Grid goes up

### ISSUE THREAD

**Issue by nehatdedinca** [codaxy/cxjs#502]
When Menu is used in Grid (specifically in a column). The scroll of the grid goes automatically up when it is clicked for the first time.

**Comment by mstijak** [comment]
I cannot reproduce this: https://codesandbox.io/s/n9j79nm97j

Please provide a little bit more details.

**Comment by nehatdedinca** [comment]
Marko, this was an issue regarding with the code of the project I am working on. My bad! Could you please delete this issue or mark it as not related to CxJS?
