### ISSUE TITLE
Open a Link in a new tab

### ISSUE THREAD

**Issue by jiripudil** [codaxy/cxjs#505]
Hello,

the LinkButton and, in turn, Link, always [open the target href in the same tab](https://github.com/codaxy/cxjs/blob/642248146a96b2656ccb344ef9a65f9e81c7a65d/packages/cx/src/widgets/nav/LinkButton.js#L79) by pushing it to history, without taking into account the modifiers of the click event – such as Ctrl or middle mouse button or Cmd on Mac – that browsers treat by opening the link in a new tab/window.

Is this intentional and if so, could you please share the reasons for it?

Thanks!

**Comment by mstijak** [comment]
This is not intentional. 
We'll investigate a little bit more about the correct behavior and update the component.
Thanks for reporting.
