### ISSUE TITLE
MsgBox component still visible after route change

### ISSUE THREAD

**Issue by andrejsimic** [codaxy/cxjs#516]
When MsgBox pops up and the user pushes browser's back button, message box stays open even though route has changed. Suggestion: allow setting MsgBox property so that the MsgBox depends on route url.

**Comment by sasatatar** [comment]
That's the thing with the MsgBox, it gets appended at the root DOM element of the entire app, so we have no control over it once it's open. I assume it wouldn't be practical to change it to cover this particular case.
Why not use a custom Window widget instead? It gives us more control, so we could have it closed from within an `onDestroy` method?

**Comment by sasatatar** [comment]
But I see your point, it's not the desired behavior to leave it open, so I'd also suggest we somehow allow more control over it. 
Currently, its static methods return a promise, so it's not possible to cancel them programmatically. We should consider changing this, or perhaps replacing it with a more advanced component, to avoid any breaking changes.
