### ISSUE TITLE
UploadButton atribute xhr.withCredentials

### ISSUE THREAD

**Issue by nemanjabodroza** [codaxy/cxjs#523]
It would be good that UploadButton has bool attribute e.g. useCredentials which would be set to xkr.withCredentials. Now there is a hack to set it in onUploadStarting method.

**Comment by mstijak** [comment]
I'm not sure. 

It's required to set `xhr.withCredentials = true` only for cross site requests.
You might need it only in development, but in that case it might be better to [setup a proxy](https://webpack.js.org/configuration/dev-server/#devserverproxy) for API calls in webpack dev server.

I'll keep the issue open for now.

**Comment by mstijak** [comment]
It's not clear what should be done. Closing...
