### ISSUE TITLE
Buffered Grid with grouping acts buggy in edit mode

### ISSUE THREAD

**Issue by sasatatar** [codaxy/cxjs#527]
There is an issue when buffered grid is used in combination with grouping. Grouping caption is not displayed, and there is some kind of record duplication on selection which causes the grid to flicker.
The issue is more visible in RowEditableGrid in edit mode.

Example: https://codesandbox.io/s/jp968r0xxv

**Comment by mstijak** [comment]
Grouping is not yet supported in buffered mode because of different row heights.
