### ISSUE TITLE
Button styled attribute

### ISSUE THREAD

**Issue by nemanjabodroza** [codaxy/cxjs#546]
Adding Styled attribute to Button widget throws warning: 
Received `true` for a non-boolean attribute `styled`.

**Comment by mstijak** [comment]
I cannot reproduce this and also I don't see the issue here. 
Why are you adding `styled` to a button?

**Comment by nemanjabodroza** [comment]
I added style attribute and than styled attribute by following warning which says all widgets with style attribute should have STYLED attribute.
Now I see that Button does not produce warning with style and no styled attribute.
