### ISSUE TITLE
Codesandbox examples are throwin an error

### ISSUE THREAD

**Issue by sasatatar** [codaxy/cxjs#548]
The following errors are thrown whenever a link is clicked:
![image](https://user-images.githubusercontent.com/5138412/59277876-3d51d400-8c61-11e9-96f7-b0442da686fe.png)

This can be seen on all Cx examples. 
https://codesandbox.io/embed/github/codaxy/cx-template-material-sidebar/tree/master/

**Comment by mstijak** [comment]
Fixed!
