### ISSUE TITLE
Grid - vertical lines mismatch

### ISSUE THREAD

**Issue by JoRomcevicS** [codaxy/cxjs#573]
Vertical line in grid header and grid body is mismatched.  ##

![Vertical lines 1](https://user-images.githubusercontent.com/35691229/67098520-a7a0f500-f1bc-11e9-9354-cdbd06dee497.PNG)
![vertical line2](https://user-images.githubusercontent.com/35691229/67098535-abcd1280-f1bc-11e9-84e0-2c9ed98dd5c7.PNG)

**Comment by mstijak** [comment]
Should work in the latest version.
