### ISSUE TITLE
LookupField - submitOnEnterKey not working

### ISSUE THREAD

**Issue by aleksinamatic** [codaxy/cxjs#575]
If LookupField selection is made by hitting the Enter key, the form that encloses it does not fire the onSubmit callback.  The event is not propagated correctly. 
`onSubmit` should fire as soon as we make a selection by hitting the enter key.
See example below.

https://fiddle.cxjs.io/?f=mQEzHqp6

**Comment by mstijak** [comment]
That's a strange request. If there are additional fields below the lookup
you would not be able to fill them in. The form should not submit if the
dropdown is open.

**Comment by aleksinamatic** [comment]
Perhaps the `Enter` key should not open the drop-down, since currently it is not possible to submit the form using only the keyboard.

**Comment by mstijak** [comment]
Resolved with #576 .
