### ISSUE TITLE
showHeader doesn't work in groupings

### ISSUE THREAD

**Issue by mstijak** [codaxy/cxjs#581]
Somehow it gets `visibility: hidden`.

**Comment by nemanjabodroza** [comment]
Now onGetGroupings.showHeader works, but Grid.ShowHeader does not work, the zero header is always visible.

**Comment by mstijak** [comment]
Fiddle?

**Comment by nemanjabodroza** [comment]
https://fiddle.cxjs.io/?f=g9BvWtfj

Grid.Scrollable sets always showHeader to true

**Comment by mstijak** [comment]
Please try with the latest version of cx.
