### ISSUE TITLE
add grid row $renderIndex

### ISSUE THREAD

**Issue by nebojsa-peric** [codaxy/cxjs#615]
Atm when defining grid's column configuration we have a grid record index available under $index alias, however this index is preserved after sorting/filtering grid, in other words it's always index of the row in original data set order. We have a requirement where we need to show index of the row in the rendering order, in other words index of the row after the sorting/grouping is applied.

**Comment by mstijak** [comment]
This is how this can be achieved. 

https://codesandbox.io/s/display-index-4bl74
