### ISSUE TITLE
Sorting issue

### ISSUE THREAD

**Issue by BesnikMahmuti-Prosperoware** [codaxy/cxjs#635]
On our project, we are using the defaultSortField="name" on a tree grid. If we have these nodes with names for example Workspace, all, any, new.  I think it should sort them alphabetical like this: 
all, any, new, Workspace and not like this: Workspace, all, any, new. No matter if the word has a capital letter.

**Comment by mstijak** [comment]
You should add [`sortOptions`](https://docs.cxjs.io/widgets/grids#sortOptions) to the grid. 

This should do the trick:

```
sortOptions: {
  sensitivity: 'base'
}
```

**Comment by BesnikMahmuti-Prosperoware** [comment]
It worked thanks.
