### ISSUE TITLE
Grid footer takes up the height of the last record, which is not always the desired behavior

### ISSUE THREAD

**Issue by sasatatar** [codaxy/cxjs#647]
![image](https://user-images.githubusercontent.com/5138412/83870842-3acc7200-a72f-11ea-908c-4de5d9a2c465.png)

**Comment by mstijak** [comment]
@sasatatar Can you please try with the latest Grid.js before this is published? Just copy it in the node_modules.

**Comment by sasatatar** [comment]
I've tested the latest Grid and the footer height seems to be OK now, but there is a small CSS issue. Footer now overlaps with the grid content: 
![image](https://user-images.githubusercontent.com/5138412/84207163-fe8f6d80-aab0-11ea-8a86-040912e61c8c.png)

**Comment by mstijak** [comment]
Please try once more.

**Comment by sasatatar** [comment]
All good now.
