### ISSUE TITLE
Optional ValidationGroup child-field setting override

### ISSUE THREAD

**Issue by sasatatar** [codaxy/cxjs#668]
Currently, as of Cx v20.7.1 form fields can override the ValidationGroup settings, e.g. if a ValidationGroup is disabled, the same setting on a respective field, being more specific, overrides it (commit id: [c2adf44c9de](https://github.com/codaxy/cxjs/commit/c2adf44c9de6756f8bc93cbd1bef6fb8237bf92f)).
In previous versions of Cx it was the other way around, ValidationGroup settings would take precedence over respective field settings within it. 

Since both behaviors have valid use-cases, it would be good if the developer could decide which one is more appropriate, via a custom flag, e.g. `overrideFieldSettings={true/false}` or something in that sense.

The implementation could rely on the optional use of the `coalesce` function, based on the flag value.

**Comment by mstijak** [comment]
Can you explain your use-case?

Field settings should always have higher priority as I see it.

**Comment by sasatatar** [comment]
We are using the `ValidationGroup` component to implement the so-called Vaulted forms, which are either locked or unlocked, depending on the Vault status. However, certain fileds can have additional `disabled` logic applied to them, given that the Vault is unlocked, which is the above described use-case where `ValidationGroup` should have precedence over respective field settings.

Currently we are forced to remove the `disabled` bindings if they are undefined, since they are interpreted as falsy, and the field is rendered enabled, although the Vault is in fact locked.

**Comment by mstijak** [comment]
Ok, I understand. Since both modes use `disabled` you should be able to specify which rule to use.

How about `<ValidationGroup disabled-bind="something" strict />`

**Comment by sasatatar** [comment]
My wording not good. I meant the order of evaluation, rather then precedence.
We are using the `ValidationGroup` component to implement the so-called Vaulted forms, which are either locked or unlocked, depending on the Vault status. However, certain fields can have additional disabled logic applied to them, but only if the Vault is unlocked. 
Currently we are forced to remove the `disabled` bindings if their values are undefined, since they are interpreted as falsy, and the field is rendered as enabled, although the Vault is in fact locked. As a result, the code is unreasonably long and unclear since we need an additional `ContentResolver` around the field, to evaluate its `disabled` binding before passing it on.

The flag does not solve the issue either, since, if the Vault is unlocked, the Field would become enabled, even if it was supposed to remain disabled, based on its individual logic.

Maybe the best approach would be to have the default setting as it is, but allow the user to pass an optional resolver function that could have custom logic to override the default behavior?

**Comment by mstijak** [comment]
Strict mode would work in that way that if `disabled` is evaluated to `true` on `ValidationGroup` it would force all children to be disabled. If the value is `false`, fields can decide for themselves.

The opposite (more common) use-case is that in the non-strict mode the field should able to be enabled by setting `disabled` to `false`, ignoring the parent settings, i.e. if one field is an exception.

**Comment by sasatatar** [comment]
That would be perfect!

**Comment by mstijak** [comment]
Published in cx@20.8.0.
