### ISSUE TITLE
Version 20.11.1 code bug

### ISSUE THREAD

**Issue by nemanjabodroza** [codaxy/cxjs#718]
Tooltip.js
> 154 |    if (parentInstance?.data.disabled) return;

**Comment by mstijak** [comment]
I wasn't aware that this is going to be a breaking change. I'll fix it.

Meanwhile, if you upgrade Babel it will go away and you'll be able to use optional chaining in your application too.

**Comment by nemanjabodroza** [comment]
Great, that is wonderful shortcut. Thank u.
