### ISSUE TITLE
TreeGrid Issue

### ISSUE THREAD

**Issue by EnjonPodrimaj** [codaxy/cxjs#736]
I have a **TreeGrid** which contains two columns, one is the title of the record (**TreeNode widget**), the other one is a button (**Menu widget**). When clicking the button **more than once**, **instead of selecting only the desired record, the $record triggers _two records_**, one is the desired record on which we wanted to perform an action, the other one **that is always being selected is _the first record_ of the grid**. This makes it hard to add a node or perform any action in the desired record as it adds it to the first record as well. 

I've checked if this bug is coming from my code but haven't found anything and I believe that this is a cx issue.

**Comment by mstijak** [comment]
I failed to reproduce it using this fiddle - https://fiddle.cxjs.io/?f=sZYpjM4g.

Do you use the `store` passed which is passed to the `onClick` handler?

**Comment by EnjonPodrimaj** [comment]
Yes, I use the store param that gets passed on 'onRowClick'. I will see if we can update the version since it might break any of our environments and then I will notify you if the issue is fixed. Thanks, Marko.

**Comment by mstijak** [comment]
Please re-open with more details.
