### ISSUE TITLE
Issues when using multiple grids with drag & drop behaviour

### ISSUE THREAD

**Issue by labiangashi-prosperoware** [codaxy/cxjs#742]
I have a couple of grids that I am loading on my page and some of them have the drag & drop behaviour (dragSource, dropZone, onDrop, onDropTest attributes).

The first two grids with this behaviour are working perfectly fine, however, the third grid behaves as if I was dragging and dropping on the first grid, taking all the attributes (for drag and drop) from the first grid. This is causing errors and exceptions on the UI side (where it is not reading onDropTest of the current grid but rather from the first grid, even though I am dragging and dropping on the third grid itself).

The stack trace comes from the file of the first grid, even though I am dragging and dropping a whole another grid which is included in a different file, it is ignoring that completely.

**Comment by mstijak** [comment]
This sounds like a bug. Would it be possible for you to try to reproduce the issue in Fiddle so someone can take a look?

**Comment by labiangashi-prosperoware** [comment]
I just built a fiddle to show you the bug but I am not sure how to make a shareable link out of it?

**Comment by labiangashi-prosperoware** [comment]
Just put this code on a fiddle somewhere and you will notice the bug:
`import { Controller, KeySelection } from "cx/ui";
import { DragHandle, FlexRow, Grid, HtmlElement } from "cx/widgets";

function insertElement(array, index, ...args) {
  return [...array.slice(0, index), ...args, ...array.slice(index)];
}

function move(store, target, e) {
  let selection = e.source.records.map(r => r.data);

  store.update(e.source.data.source, array =>
    array.filter((a, i) => selection.indexOf(a) == -1)
  );

  if (e.source.data.source == target)
    e.source.records.forEach(record => {
      if (record.index < e.target.insertionIndex) e.target.insertionIndex--;
    });

  store.update(target, insertElement, e.target.insertionIndex, ...selection);
}

class AppController extends Controller {
  init() {
    this.store.delete("grid1");
    this.store.delete("grid2");
    this.store.delete("grid3");

    this.store.set(
      "grid1",
      Array.from({ length: 15 }, (_, c) => ({
        id: c + 1,
        name: "Item " + (c + 1),
        type1: "bug",
        number: Math.random() * 100
      }))
    );

    this.store.set(
      "grid2",
      Array.from({ length: 15 }, (_, c) => ({
        id: 10000 + c + 1,
        name: "Item " + (c + 1),
        type2: "bug",
        number: Math.random() * 100
      }))
    );

    this.store.set(
      "grid3",
      Array.from({ length: 15 }, (_, c) => ({
        id: 10000 + c + 1,
        name: "Item " + (10001 + c),
        type3: "bug",
        number: Math.random() * 100
      }))
    );
  }
}

export const App = (
  <cx>
    <div style="padding:30px" controller={AppController}>
      <h3>Grid to Grid Drag & Drop (Test Grid 1, particularly lines 89-101</h3>
      <FlexRow>
        <Grid
          records:bind="grid1"
          columns={[
            {
              field: "name",
              header: "Name",
              sortable: true,
              style: "width: 150px"
            },
            {
              field: "type1",
              header: "Bug or not",
              style: "width: 300px"
            },
            {
              field: "number",
              header: "Number",
              format: "n;2",
              sortable: true,
              align: "right"
            }
          ]}
          dragSource={{ data: { type: "record", source: "grid1" } }}
          onDropTest={e => {
            console.log("rec", e.source.record);
            console.log("rec data", e.source.record.data);
            console.log("rec data type1:", e.source.record.data.type1);
            console.log(
              "rec data type1 tolowercase:",
              e.source.record.data.type1.toLowerCase()
            );
            return;
            e.source.data.type == "record" &&
              e.source.record.data.type1.toLowerCase() !== "bug";
          }}
          onDrop={(e, { store }) => move(store, "grid1", e)}
          selection={{ type: KeySelection, multiple: true, bind: "s1" }}
        />
        <div style="width:100px" />
        <Grid
          records:bind="grid2"
          columns={[
            {
              items: (
                <cx>
                  <DragHandle style="cursor:move">☰</DragHandle>
                </cx>
              )
            },
            {
              style: "width: 300px",
              field: "name",
              header: "Name",
              sortable: true
            },
            {
              field: "type2",
              header: "Bug or not",
              style: "width: 300px"
            },
            {
              field: "number",
              header: "Number",
              format: "n;2",
              sortable: true,
              align: "right"
            }
          ]}
          dragSource={{
            mode: "copy",
            data: { type: "record", source: "grid2" }
          }}
          dropZone={{ mode: "insertion" }}
          onDropTest={e =>
            e.source.data.type == "record" &&
            e.source.record.data.type2.toLowerCase() !== "bug"}
          onDrop={(e, { store }) => move(store, "grid2", e)}
        />
        <div style="width:100px" />
        <Grid
          records:bind="grid3"
          columns={[
            {
              items: (
                <cx>
                  <DragHandle style="cursor:move">☰</DragHandle>
                </cx>
              )
            },
            {
              style: "width: 300px",
              field: "name",
              header: "Name",
              sortable: true
            },
            {
              field: "type3",
              header: "Bug or not",
              style: "width: 300px"
            },
            {
              field: "number",
              header: "Number",
              format: "n;2",
              sortable: true,
              align: "right"
            }
          ]}
          dragSource={{
            mode: "copy",
            data: { type: "record", source: "grid3" }
          }}
          dropZone={{ mode: "insertion" }}
          onDropTest={e =>
            e.source.data.type == "record" &&
            e.source.record.data.type3.toLowerCase() !== "bug"}
          onDrop={(e, { store }) => move(store, "grid3", e)}
        />
      </FlexRow>
    </div>
  </cx>
);
`

**Comment by labiangashi-prosperoware** [comment]
Got it: https://fiddle.cxjs.io/?f=8nhO8aRD

**Comment by mstijak** [comment]
There are some problems with your example. I made a new fiddle and removed `toLowerCase` calls, so it works now.

https://fiddle.cxjs.io/?f=8mTRrax5

Please explain a little bit more what is the problem and the expected behavior.

**Comment by labiangashi-prosperoware** [comment]
I can still see the same fiddle, including the `toLowerCase()` call.

**Comment by mstijak** [comment]
Maybe I forgot to save. It should be ok if you refresh the page.

**Comment by labiangashi-prosperoware** [comment]
I removed the `toLowerCase()` from my `onDropTest` attribute and now it is searching for both of the grids. It is evaluating the first grid's function before moving on to the actual grid I am doing the drag and drop now.

Removing the `toLowerCase()` apparently works as a workaround (It won't throw an error and therefore abruptly stop the evaluation) but I still don't think it fixed the underlying issue. Nevertheless, if you need more information and want to fix the underying issue, let me know and I'll provide you with something.

**Comment by mstijak** [comment]
`onDropTest` is used to check if the grid should react to the object that is being dragged. This function is repeatably invoked for all drop zones. If you return false, the grid will not show the placement indicator when you hover over it.
