### ISSUE TITLE
Tooltip issue

### ISSUE THREAD

**Issue by EnjonPodrimaj** [codaxy/cxjs#750]
Hello CX team, I am trying to add a rich tooltip for a TextArea widget. This tooltip is going to contain a code snippet. The issue is that everything is inline and the code snippet is cumbersome to read. 

I have tried using Template Strings from JS and even tried normal strings with adding '\n' for a new line, but that doesn't do the job either. Is this a limitation or can this be added to tooltips? Any help is appreciated.
![Screenshot_82](https://user-images.githubusercontent.com/56723777/111171046-d9321180-85a4-11eb-852a-8553823d1940.png)

**Comment by mstijak** [comment]
You should check the "Component inside" example in the docs -
https://docs.cxjs.io/widgets/tooltips. You should wrap the code in the pre
element.

**Comment by EnjonPodrimaj** [comment]
We fixed this by working with **character entities of HTML**, setting **plainText** to **false** and adding **'preserveWhitespace'** to our div. Thanks Marko!
![Screenshot_87](https://user-images.githubusercontent.com/56723777/111316642-badf1b00-8663-11eb-8fae-f20b17a03a81.png)
![Screenshot_88](https://user-images.githubusercontent.com/56723777/111316768-d3e7cc00-8663-11eb-9431-be8d8599d82b.png)

 to our div.

**Comment by mstijak** [comment]
Glad it worked. I still think you should try the `pre` element instead of the `div`.
