### ISSUE TITLE
Checkbox onClick

### ISSUE THREAD

**Issue by EnjonPodrimaj** [codaxy/cxjs#751]
Hi CX team, I am trying to add an onClick property in a checkbox widget but I cannot do that, is there a way around this? 
Additional info: the checkbox is located under an items prop of a [grid.]
![Screenshot_8](https://user-images.githubusercontent.com/56723777/112615214-7e10e200-8e22-11eb-864f-09eb9a957cfc.png)

**Comment by mstijak** [comment]
You should define a set function instead of using value-bind.

https://docs.cxjs.io/concepts/data-binding#setters

**Comment by EnjonPodrimaj** [comment]
I was not able to add a function call from the controller, however, I added a trigger in the controller and then created a store binding for that purpose and that solved the issue for me. Thanks Marko!
![Screenshot_9](https://user-images.githubusercontent.com/56723777/112629143-33986100-8e34-11eb-9859-f6066df18a63.png)
