### ISSUE TITLE
New icon integration

### ISSUE THREAD

**Issue by EnjonPodrimaj** [codaxy/cxjs#754]
Hi CX Team, I'm trying to add other icons to our CAM project. The issue is that only FontAwesome icons can be added, how could one add other icons or images in the icon param of a tree-grid (tree-node respectively). 

The reason why I need to do this is that we need to add some icons from O365 and FontAwesome doesn't have any of those icons. Any help is appreciated.

**Comment by mstijak** [comment]
This can be solved by using prefixes for icon names and checking that
within the icon factory method.
For example, if an icon starts with `fa-` render font-awesome, otherwise,
render something else.

**Comment by EnjonPodrimaj** [comment]
Thanks Marko, that solved the issue for me.
