### ISSUE TITLE
Automatically close Dropdown when we click outside of it

### ISSUE THREAD

**Issue by OKremenovic** [codaxy/cxjs#755]
It would be good if **Dropdown** component had a property like _dismissOnFocusOut_. 
Closing dropdown with an outside click should probably be the default dropdown state.

**Comment by mstijak** [comment]
It appears that `dismissOnFocusOut` is already implemented. Can you please check it?

**Comment by OKremenovic** [comment]
I checked it and it doesn't seem to be working. [Fiddle example](https://fiddle.cxjs.io/?f=XG2hY6VW)

**Comment by mstijak** [comment]
It works. The dropdown first needs to receive focus which is a bit tricky to do.

https://fiddle.cxjs.io/?f=hysUzFQ2
