### ISSUE TITLE
Infinite Scroll Grid issue

### ISSUE THREAD

**Issue by EnjonPodrimaj** [codaxy/cxjs#776]
Hello CX team, I'm having this issue with an infinite scrolling grid where after scrolling once the vertical scroller goes to the end and there is no way to scroll lower to see other results. Here is my current Grid configuration, do you have any idea what may be causing the issue? - Thanks prehand. 
![image](https://user-images.githubusercontent.com/56723777/123965551-d8d35000-d9b4-11eb-86a6-d6b262926584.png)

**Comment by mstijak** [comment]
Hi Enjon. Can you explain a little bit how your `loadNextPageUsers` method works. Specifically, do you use `totalRecordCount` or not?
