### ISSUE TITLE
ContentPlaceholder inside Overflow Menu

### ISSUE THREAD

**Issue by Njegos1997** [codaxy/cxjs#884]
When we use a content placeholder to put items inside a menu with overflow, all the items inside the content placeholder are not visible in the collapsed dropdown.

[See fiddle](https://fiddle.cxjs.io/?f=QNZIG7ZH).

Is this expected behaviour?

![overflow placeholder](https://user-images.githubusercontent.com/85864173/133425831-f43b9b6e-eccc-4c63-bdf3-ac6f27a61917.gif)

**Comment by mstijak** [comment]
Unfortunately, this cannot work. With menu overflow, there are actualy two ContentPlaceholders with the same name. CxJS doesn't support filling two ContentPlaceholders at the same time.

Is it possible to achieve the same functionality differently?

**Comment by Njegos1997** [comment]
Yes, it's possible.

Thank you.
