### ISSUE TITLE
Hover effect on grid rows with fixed columns

### ISSUE THREAD

**Issue by OKremenovic** [codaxy/cxjs#886]
Currently, when we hover over a cell in the fixed column, the hover effect is applied only to the part of the row that belongs to the fixed columns. 
It should work the same way as row selected state.

![image](https://user-images.githubusercontent.com/17080238/134313749-392a4fb7-5364-48e6-b082-5a534ff0af19.png)

**Comment by mstijak** [comment]
This is supported using the HoverSync component. Here's an example - https://fiddle.cxjs.io/?f=d5T9C5tD
