### ISSUE TITLE
TreeGrid custom element

### ISSUE THREAD

**Issue by EnjonPodrimaj** [codaxy/cxjs#906]
Hello CX Team,

I was wondering if there is a way to add custom elements, like the one in the screenshot, to the TreeGrid records?
![image](https://user-images.githubusercontent.com/56723777/142624338-1fe343b5-0468-420f-8da4-dcecc31fdc08.png)

**Comment by ognjenst** [comment]
Hi @EnjonPodrimaj. Should these elements be visible all the time, or only when a record is clicked?
