### ISSUE TITLE
TreeGrid refresh issue

### ISSUE THREAD

**Issue by EnjonPodrimaj** [codaxy/cxjs#907]
Hey CX Team, I'm having trouble with CXJS's responsiveness. When clicking **Add Template**, I'm adding a new record at the first position of the array and assigning that to the grid, but it's not showing up until I click something else in the TreeGrid. Can this be solved somehow without the need to click on the grid? Thanks in advance.

Recording
![TreeGrid Issue](https://user-images.githubusercontent.com/56723777/142664246-e0430259-add7-405f-9602-b517a29e8ec6.gif)

Code: 
`showAddTemplate() {
        if (!this.store.get("$page.templateEditor.addingTemplate")) {
            this.store.set("$page.templateEditor.addingTemplate", true);

            this.store.update("$page.templateEditor.templates", (templates) => {
                let unConfirmedTemplate = {
                    $level: 0,
                    name: "",
                    id: generateUniqueId(),
                    icon: "te-template",
                    beingAdded: true,
                };

                templates.unshift(unConfirmedTemplate);
                return templates;
            })
        }
    }`

**Comment by ognjenst** [comment]
Hi @EnjonPodrimaj. This should work if all bindings are correct. Could you please provide us with a fiddle example, so we can take a closer look? [Fiddle](https://fiddle.cxjs.io/)

**Comment by mstijak** [comment]
CxJS uses dumb change detection which requires that a new instance is created whenever you change an object or an array.

Changing the last line to 
```
return [unConfirmedTemplate, ...templates];
```
should do the trick.

**Comment by EnjonPodrimaj** [comment]
@mstijak that solution worked perfectly. Thanks so much, @mstijak and @ognjenst!
