### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [codaxy/cxjs#913]
Hey there!

I belong to an open source security research community, and a member (@wjddnjs33) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by mstijak** [comment]
Thanks for reaching out. I have added a minimal [SECURITY.md](https://github.com/codaxy/cxjs/blob/master/SECURITY.md) file as proposed.

**Comment by JamieSlome** [comment]
@mstijak - thanks 👋 

Just for reference, the report can be found here:

https://huntr.dev/bounties/60fb241b-1026-448a-b8f5-0ff196b5b9b1/

It is private and only accessible to maintainers whilst unfixed. We will follow up with an e-mail that will give you special access to the report.

**Comment by mstijak** [comment]
Answered there.
