### ISSUE TITLE
Bug when using radio button with list

### ISSUE THREAD

**Issue by Njegos1997** [codaxy/cxjs#934]
When we change selection from one item to another by selecting the radio button inside the list, cxs-cursor class isn't removed from the previous selection, so background color is applied even if the selection is not on that item.

Fiddle link: https://fiddle.cxjs.io/?f=zr9BSg1S

![RadioListBug](https://user-images.githubusercontent.com/85864173/157241711-567ed496-d9f2-4868-b45e-1fb7a18981ee.gif)

**Comment by mstijak** [comment]
Cursor is independent from selection. It's used for going through the list using the keyboard.

**Comment by mstijak** [comment]
I'm going to close this since this is not a real bug.

To achieve the desired behavior you might try setting "pointer-events: none" on the radio buttons.
