### ISSUE TITLE
Add support for "fixedFooter" in non scrollable grids

### ISSUE THREAD

**Issue by nebojsa-peric** [codaxy/cxjs#942]
![image](https://user-images.githubusercontent.com/30226963/158592387-1d302856-013d-4398-b069-f5f736e9ba44.png)
We have a use case where we print grids with fixed footer, those grids cannot be scrollable thus making the footer disappear, so it would be nice to render plain footer in such a use case.

**Comment by mstijak** [comment]
There is an experimental branch that solves it. Can you please check if that works before we merge it in.

https://github.com/codaxy/cxjs/tree/feat/fixed-footer-printing

**Comment by mstijak** [comment]
This should be resolved in the latest `beta`.
