### ISSUE TITLE
add typescript typings / integrate with build system

### ISSUE THREAD

**Issue by nahuel** [codaxy/cxjs#95]
is planned?

**Comment by mstijak** [comment]
We don't have any plans yet, however, but this is something that we should definitely do.

Regarding TypeScript, Cx needs `babel-plugin-transform-cx-jsx` to transform JSX. Based on my limited knowledge of TypeScript,  it's not possible to write a similar plugin, which means that both TypeScript compiler and Babel would have to be used in a TypeScript based project that uses Cx.

Let's leave this issue open for now.

**Comment by david-bouyssie** [comment]
Why not use TSX files instead of JSX in this kind of projects?
https://www.typescriptlang.org/docs/handbook/jsx.html

**Comment by mstijak** [comment]
We started working on this and it's halfway done. I just made it public so you can take a look at it here:

https://github.com/codaxy/cx-typescript-boilerplate

There are two issues for now:

1. TypeScript doesn't support XML namespaces, so `value:bind="x"` syntax doesn't work inside JSX. You'll have to use value={bind("x")}.

2. TypeScript removes unused HtmlElement import, so you have to make up some use of it. I would be very grateful for a suggestion how to resolve this better. My last resort plan is to create a new Babel plugin which would restore the reference.

**Comment by mstijak** [comment]
Anyway, we reported the issue of TypeScript not supporting XML namespaces in JSX a while ago. 
Please consider giving a thumb if you're interested in this.

https://github.com/Microsoft/TypeScript/issues/11833

**Comment by david-bouyssie** [comment]
Thank you for your quick answer.
I'm not sure to understand. Is it a Visual Studio or a TypeScript compiler limitation?

Side note:
I would like to switch from ExtJS to Cx.
I recently developed a glue between TypeScript and ExtJS: https://github.com/david-bouyssie/TypExt
In the meantime the ExtJS devs released extjs-reactor (https://github.com/sencha/extjs-reactor) but the rendering is performed by ExtJS itself not React, so there is no performance benefit.
Cx seems to embrace the React rendering so it might be a good option for my project, but TypeScript is now a real need for me...

**Comment by mstijak** [comment]
It's a TypeScript compiler limitation which forbids usage of XML namespaces in JSX, however, the alternative syntax should work just fine. 

There is still a lot of work on providing full type definitions for all Cx components. I plan to work on this next week, so I'll keep you posted.

**Comment by nahuel** [comment]
@mstijak just a side note, check the trick used in https://github.com/kube/monolite to make paths statically typed and intellisense compatible, maybe it can be replicated for the paths used in the cx store operations.

**Comment by mstijak** [comment]
@nahuel; This is very interesting. I guess if the shape of the data in the store is declared, then this would work. On the other side, data views would probably be difficult to implement. E.g. Sandbox enables that each page has its data exposed under `$page` (or some other alias), but maybe that can be resolved too.
This is something we will definitely consider after typings are complete. Thanks for the tip.

**Comment by mstijak** [comment]
We made very good progress, however, it's a big task and it will take some time. Our plan is to complete type definitions in three phases:

1. All widgets defined using `any` props
2. Proper widget type definitions
3. Add JSDoc comments from our documentation

Phase 1 is almost complete, and we started with 2 & 3 in parallel. 

We reached the first milestone, so you should take another look at the [cx-typescript-boilerplate](https://github.com/codaxy/cx-typescript-boilerplate) project. It's now a full-blown application in which we ported a few examples and applied the new Material Design theme. Quick demo here: http://alive-chairs.surge.sh

Code completion works very well in Visual Studio Code:
![image](https://cloud.githubusercontent.com/assets/433394/24505680/12aee97e-155b-11e7-9b0b-67ea8444887d.png)

Let me know if you need any help.

**Comment by mstijak** [comment]
I just published cx@17.5.0 which includes TypeScript definitions in the package and updated the `cx-typescript-boilerplate` project. Please check it out and report any issues you find.  

There is still remaining work on providing JSDoc comments, however, typings should be complete. 🎉

**Comment by mstijak** [comment]
I'm closing this issue since TypeScript support is in pretty good shape right now. New [Gallery](https://cxjs.io/gallery) project is written in TypeScript.
