### ISSUE TITLE
Issue with lookups inside scrollable containers

### ISSUE THREAD

**Issue by mstijak** [codaxy/cxjs#960]
![image](https://user-images.githubusercontent.com/433394/164216659-4af3c48f-27f0-420b-b50c-404a47fdf5d4.png)

**Comment by nebojsa-peric** [comment]
@mstijak @OKremenovic Could it be related to this change on `MenuItem`:
![image](https://user-images.githubusercontent.com/30226963/164217464-7d09b89a-9511-4762-a6af-1b7911159e90.png)

**Comment by mstijak** [comment]
Fixed with #963.
