### ISSUE TITLE
Loading folders on expand is causing to trigger twice

### ISSUE THREAD

**Issue by ali-morina** [codaxy/cxjs#975]
I have a function that's called when a folder is expanded to fetch its children, but, doing so it's causing to fetch children twice. Not sure if this is a bug or an issue from my side.

"cx": "^20.4.5",
"cx-react": "^17.10.0",

**Grid:**

<Grid
      records-bind="selectedWorkspace"
      mod="tree"
      class="treenode-grid"
      style={{
        maxHeight: '300px',
        overflow: 'auto',
        flex: '1 1 0%',
        background: 'white',
        height: '100%',
      }}
      keyField="id"
      filterParams-bind="$page.filtered"
      defaultSortField="has_documents"
      defaultSortDirection='DESC'
      sortOptions={'sensitivity: base'}
      emptyText-bind="$page.selectedWorkspaceMessage"
      selection={{
        type: KeySelection,
        bind: '$page.selectedWorkspace.selection',
      }}
      dataAdapter={{
        type: TreeAdapter,
        load: async (context, { controller, store }, node) =>
          controller.fetchChildren(node, { store }),
      }}
      visible-expr="!{$page.workspaceLoader}"
      columns={[
        {
          header: '',
          items: (
            <cx>
              <TreeNode
                class="flex-row interaction-item"
                expanded-bind="$record.$expanded"
                level-bind="$record.$level"
                loading-bind="$record.$loading"
                leaf-bind="$record.$leaf"
                icon-expr="{$record.$loading} ? 'fa-spinner fa-spin' : {$record.icon} || {$record.$icon}"
                loadingIcon="fa-spinner fa-spin"
              >
                <div className="treenode-form inline-form">
                  <Radio
                    value={{
                      bind: 'moveWorkspaces.selectedFolder',
                      set: (value, { store }) => {
                        const oldId = store.get(
                          'moveWorkspaces.selectedFolder.id'
                        );
                        const newId = value && value.id;
                        if (oldId == newId) {
                          store.delete('moveWorkspaces.selectedFolder');
                        } else {
                          store.set('moveWorkspaces.selectedFolder', value);
                          store.set(
                            '$page.queryResults',
                            store.get('$page.queryResults').map(r =>
                              Object.assign({}, r, {
                                selected: false,
                              })
                            )
                          );
                        }
                      },
                    }}
                    option-bind="$record"
                    visible={computable(
                      '$page',
                      'viewMoveFoldersDocumentsButton',
                      (page, permission) =>
                        setVisibility(page, permission, [WORKSPACE])
                    )}
                  />
                  <span text-bind="$record.name" />
                  <Button
                    tooltip="Show documents"
                    icon="fa-file-export fas"
                    visible-bind="$record.has_documents"
                    class="s-info"
                    mod="hollow"
                    style="margin-left: 5px;"
                    onClick={(e, { store, controller }) => {
                      store.set($folder.offset, 0);
                      store.set($folder.selectedFolder, store.get('$record'));
                      controller.getDocumentsForFolder(e, { store });
                    }}
                    text={{
                      expr: "{$record.loading} ? 'Loading...' : null",
                    }}
                  />
                </div>
              </TreeNode>
            </cx>
          ),
        },
      ]}
    />

**Comment by ognjenst** [comment]
Hi @ali-morina. I see that you are calling the ```fetchChildren()``` function in your load call and that you are passing the store inside. Could you post that function here as well? 

Usual implementation of this function is only to return new records, as you can see in the fiddle example [here](https://fiddle.cxjs.io/?f=riuObfzq#). Grid will automatically update the tree structure.

**Comment by ali-morina** [comment]
Hi @ognjenst this is the current function we are using to fetch children, I am deleting children because by default API will return children: [], and this would not cause the function to be triggered because it already included the children's property as empty. Thank you so much for helping me :)


async fetchChildren(node, { store }) {
    try {
      const isExternal = store.get('searchOnExtSystem');
      const { data, repoList, record } = store.get(
        'fetchChildFoldersWorkspaceData'
      );
      const { repo, system, database } = data;
      const server = getServerFromRepo(repoList, repo, system);

      const payload = {
        system,
        folderId: node.internalId || node.id,
        database,
        repo,
        children: false,
        type: 'folder',
        link: generateLink(server, node.internalId || node.id),
      };
      if (isExternal && system === CAM_SYSTEMS.NETDOC) {
        payload.link = record.url;
      }
      if (!isExternal && system === CAM_SYSTEMS.NETDOC) {
        payload.workspaceId = payload.folderId;
      }
      if (isExternal && system === CAM_SYSTEMS.IMANAGE) {
        payload.workspaceId = payload.folderId;
      }
      const { Item = {} } =
        (await api.fetchChildFoldersWorkspace(payload)) || {};
      const children =
        (Item &&
          Item.folder_template_details &&
          Item.folder_template_details.children) ||
        [];

      // delete children property to allow to fetch folders on expand
      return helperFunction.formatChildFoldersToTreeGrid(children).map(i => {
        if (i.children) delete i.children;
        if (i.$children) delete i.$children;
        return i;
      });
    } catch (error) {
      console.error('Error fetching children', error);
      return [];
    } finally {
      store.set('$record.$loading', false);
    }
  }

**Comment by ognjenst** [comment]
@ali-morina I would suggest you try to use ```TreeNode``` in the items section, inside of ```Grid```. You can find the documentation and the Fiddle examples [here](https://docs.cxjs.io/widgets/tree-grid#-code-treenode-code-configuration). This will give you good control inside of the grid, and its expanding records. This could solve your problem.

Also, your records should contain a boolean property called ```$leaf```, which will let the grid know if that node should be expanded or not. 

If the response from the API contains ```children : []```, that should not be a problem, because Grid by default uses ```$children``` as the key where it saves all the fetched records. So, if the server is not returning ```$children``` as well, you don't need the logic for filtering that property out in your objects. Just return an array of new records.

A few improvements are also possible: 

I see that you are controlling the selection in the grid with radio buttons. You can also take a look at ```Key Selection``` [here](https://docs.cxjs.io/concepts/selections#key-selection), as Grid supports the selection of its records out-of-the-box. 

If you need any help, feel free to reach out again. :)
